blank_issues_enabled: false
contact_links:
  - name: NSM Operations Center
    url: https://NSM.no/TS-contact
    about: For urgent TS-level issues only
  - name: Mandate Compliance Questions
    url: https://NSM.no/mandate-2026
    about: Questions about NSM Mandate 2026 compliance


